package com.example.art.model;

public enum Delivery {
    UNKNOWN,
    REGISTERED,
    RESERVED,
    CANCELLATION_REQUESTED,
    CANCELLED,
    SHIPPED,
    DOWNLOAD_AVAILABLE,
    DELIVERED,
    RETURN_REQUESTED,
    RETURNED,
    RETURN_REJECTED,
    RETURN_CANCELLED,
    LOST,
    MIXED,
    PAYMENT_EXPIRED,
    PAYMENT_CANCELLED,
    PAYMENT_FAILED
}
